name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install

    - name: Update dependencies
      run: composer update

  tests:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    - uses: actions/checkout@v2

    # - name: Setup PHP
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '7.4'

    # - name: Install dependencies
    #   run: composer install

    # - name: Update dependencies
    #   run: composer update

    - name: Run test suite
      run: composer run-script test

  deploy:
    runs-on: ubuntu-latest

    needs: [build, tests]

    steps:
    - uses: actions/checkout@v2
    
    - name: Mensajito
      run: echo "Aquí estaría el código para Delivery/Deploy"

